resource "random_string" "lambda" {
  length  = 8
  special = false
  upper   = false

  lifecycle {
    ignore_changes = [
      special,
      upper,
    ]
  }
}

resource "random_string" "flask_secret_key" {
  length  = 32
  special = false
  upper   = false

  lifecycle {
    ignore_changes = [
      special,
      upper,
    ]
  }
}

locals {
  flask_secret_key = sensitive(random_string.flask_secret_key.result)
  name             = "saml2oauth-${random_string.lambda.result}"
  saml_secret_name = "saml-idp-keypair-${random_string.lambda.result}"
}

# =============================================================================
# Lambda Build/Fetch Logic
# =============================================================================

# Build Lambda package locally
resource "null_resource" "build_lambda" {
  count = var.lambda_source == "local" ? 1 : 0

  triggers = {
    # Rebuild when source files change
    source_hash = sha256(join("", [
      for f in fileset("${path.module}/src", "*.py") : filesha256("${path.module}/src/${f}")
    ]))
    requirements_hash = filesha256("${path.module}/src/requirements.txt")
  }

  provisioner "local-exec" {
    command     = "./build.sh"
    working_dir = path.module
  }
}

# Fetch Lambda package from GitHub releases
resource "null_resource" "fetch_lambda" {
  count = var.lambda_source == "github" ? 1 : 0

  triggers = {
    release_tag = var.github_release_tag
  }

  provisioner "local-exec" {
    command = <<-EOT
      mkdir -p ${path.module}/dist
      curl -L -o ${path.module}/dist/lambda.zip \
        "https://github.com/${var.github_repo}/releases/download/${var.github_release_tag}/lambda.zip"
    EOT
  }
}

# =============================================================================
# SAML Signing Keypair (generated by Terraform, not Lambda)
# =============================================================================

# Generate RSA private key for SAML signing
resource "tls_private_key" "saml_signing" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

# Generate self-signed certificate for SAML signing
resource "tls_self_signed_cert" "saml_signing" {
  private_key_pem = tls_private_key.saml_signing.private_key_pem

  subject {
    common_name  = var.IDP_COMMON_NAME
    organization = "Shim IdP"
    country      = "GB"
  }

  validity_period_hours = 87600 # 10 years

  allowed_uses = [
    "digital_signature",
  ]
}

# Store keypair in Secrets Manager
resource "aws_secretsmanager_secret" "saml_keypair" {
  name                    = local.saml_secret_name
  recovery_window_in_days = 0 # Allow immediate deletion for dev/test
}

resource "aws_secretsmanager_secret_version" "saml_keypair" {
  secret_id = aws_secretsmanager_secret.saml_keypair.id
  secret_string = jsonencode({
    private_key_pem = tls_private_key.saml_signing.private_key_pem
    cert_pem        = tls_self_signed_cert.saml_signing.cert_pem
  })
}

# =============================================================================
# Lambda Function
# =============================================================================

resource "aws_lambda_function" "lambda" {
  depends_on = [
    null_resource.build_lambda,
    null_resource.fetch_lambda,
    aws_secretsmanager_secret_version.saml_keypair,
  ]

  filename         = "${path.module}/dist/lambda.zip"
  source_code_hash = filebase64sha256("${path.module}/dist/lambda.zip")

  function_name = local.name
  handler       = "lambda_function.lambda_handler"
  runtime       = "python3.13"

  role = aws_iam_role.lambda_role.arn

  memory_size = 384
  timeout     = 30

  environment {
    variables = {
      ENVIRONMENT              = "prod"
      FLASK_SECRET_KEY         = local.flask_secret_key
      SAML_KEYPAIR_SECRET_NAME = local.saml_secret_name
      OAUTH_CLIENT_ID          = var.OAUTH_CLIENT_ID
      OAUTH_CLIENT_SECRET      = sensitive(var.OAUTH_CLIENT_SECRET)
      SCIM_URL                 = var.SCIM_URL
      SCIM_ACCESS_TOKEN        = sensitive(var.SCIM_ACCESS_TOKEN)
      SP_ACS_URL               = var.SP_ACS_URL
      SP_ENTITY_ID             = var.SP_ENTITY_ID
    }
  }
}

resource "aws_lambda_function_url" "lambda" {
  function_name = aws_lambda_function.lambda.function_name
  authorization_type = "NONE"
}
resource "aws_iam_role" "lambda_role" {
  name               = local.name
  assume_role_policy = data.aws_iam_policy_document.arpd.json
}

resource "aws_cloudwatch_log_group" "lambda_lg" {
  name              = "/aws/lambda/${local.name}"
  retention_in_days = var.LOG_RETENTION_DAYS
}

# See also the following AWS managed policy: AWSLambdaBasicExecutionRole
resource "aws_iam_policy" "lambda_policy" {
  name        = local.name
  path        = "/"
  description = "IAM policy for ${local.name}"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "logs:CreateLogGroup",
        ]
        Effect   = "Allow"
        Resource = "arn:aws:logs:*:*:*"
      },
      {
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Effect   = "Allow"
        Resource = "arn:aws:logs:*:*:log-group:/aws/lambda/${local.name}:*"
      },
      {
        Action = [
          "secretsmanager:GetSecretValue",
        ]
        Effect   = "Allow"
        Resource = aws_secretsmanager_secret.saml_keypair.arn
      }
    ]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_pa" {
  role       = aws_iam_role.lambda_role.name
  policy_arn = aws_iam_policy.lambda_policy.arn
}

data "aws_iam_policy_document" "arpd" {
  statement {
    sid    = "AllowAwsToAssumeRole"
    effect = "Allow"

    actions = ["sts:AssumeRole"]

    principals {
      type = "Service"

      identifiers = [
        "lambda.amazonaws.com",
      ]
    }
  }
}
